export const PORTFOLIO_CARDS = [
  {
    id: 1,
    title: 'Serving up AR fun',
    image: 'https://images.unsplash.com/photo-1552820728-8ac41f1ce891?w=1200&h=800&fit=crop',
    description: 'Innovative AR experience for interactive gaming and entertainment that revolutionized how users engage with digital content.',
    testimonial: 'The reaction to the technology used in the Tennisables AR project has been extremely positive. The result is high quality, fun and innovative.',
    rating: 5,
    link: '#project-1',
  },
  {
    id: 2,
    title: 'Building the Future',
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200&h=800&fit=crop',
    description: 'A comprehensive platform that transformed the way companies manage their digital infrastructure and streamline operations.',
    testimonial: 'Outstanding execution and attention to detail. Exceeded all expectations.',
    rating: 5,
    link: '#project-2',
  },
  {
    id: 3,
    title: 'Creative Excellence',
    image: 'https://images.unsplash.com/photo-1460925895917-adf4e565db42?w=1200&h=800&fit=crop',
    description: 'A creative studio project that blended design, technology, and storytelling to create memorable brand experiences.',
    testimonial: 'Perfect blend of creativity and technical excellence.',
    rating: 5,
    link: '#project-3',
  },
  {
    id: 4,
    title: 'Digital Transformation',
    image: 'https://images.unsplash.com/photo-1517694712026-d21404687b55?w=1200&h=800&fit=crop',
    description: 'Enterprise solution that modernized legacy systems and improved operational efficiency by 300%.',
    testimonial: 'Game-changer for our business operations.',
    rating: 5,
    link: '#project-4',
  },
  {
    id: 5,
    title: 'Innovation Hub',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=1200&h=800&fit=crop',
    description: 'An ecosystem designed to foster innovation and collaboration among creative and technical teams.',
    testimonial: 'Transformed our workflow and boosted productivity.',
    rating: 5,
    link: '#project-5',
  },
];
